id = "davidgape89/dnf-updates"
name = "DNF updates"
version = "0.0.2"
min_noctalia = "5.0.0"
author = "davidgape89"
license = "MIT"
tags = ["dnf", "updates", "fedora"]
icon = "refresh"
description = "A plugin that checks if there are any software updates available."

[[setting]]
key = "cache_refresh"
type = "int"
label = "Cache refresh interval"
description = "Cache refresh time in minutes"
default = 5
min = 1
max = 60

[[setting]]
key = "service_refresh"
type = "int"
label = "Service refresh interval"
description = "Service refresh time in minutes"
default = 1
min = 1
max = 60

[[widget]]
id = "dnf-updates"
entry = "dnf-updates.luau"

  [[widget.setting]]
  key = "updated-glyph"
  type = "glyph"
  label = "Updated glyph"
  description = "Glyph shown before the label when system updated."
  default = "refresh"

  [[widget.setting]]
  key = "not-updated-glyph"
  type = "glyph"
  label = "Not updated glyph"
  description = "Glyph shown before the label when system not updated."
  default = "refresh-alert"

  [[widget.setting]]
  key = "needs-restart-glyph"
  type = "glyph"
  label = "Needs restart glyph"
  description = "Glyph shown before the label when system needs restart."
  default = "refresh-dot"

  [[widget.setting]]
  key = "show_glyph"
  type = "bool"
  label = "Show glyph"
  default = true

  [[widget.setting]]
  key = "show_label"
  type = "bool"
  label = "Show label"
  default = true

[[service]]
id = "updates-service"
entry = "updates-service.luau"
