id = "davidgape89/dnf-updates"
name = "Dnf Updates"
version = "0.1.0"
plugin_api = 3
min_noctalia = "5.0.0"
author = "davidgape89"
icon = "refresh"
description = "A plugin that checks if there are any software updates available."
dependencies = ["dnf"]
tags = ["dnf", "updates", "fedora"]

[[setting]]
key = "cache_refresh"
type = "int"
label_key = "cacheRefresh.label"
description_key = "cacheRefresh.description"
default = 5
min = 1
max = 60

[[widget]]
id = "updates-widget"
entry = "updates-widget.luau"

  [[widget.setting]]
  key = "updated-glyph"
  type = "glyph"
  label_key = "updatedGlyph.label"
  description_key = "updatedGlyph.description"
  default = "refresh"

  [[widget.setting]]
  key = "not-updated-glyph"
  type = "glyph"
  label_key = "notUpdatedGlyph.label"
  description_key = "notUpdatedGlyph.description"
  default = "refresh-alert"

  [[widget.setting]]
  key = "needs-restart-glyph"
  type = "glyph"
  label_key = "needsRestartGlyph.label"
  description_key = "needsRestartGlyph.description"
  default = "refresh-dot"

  [[widget.setting]]
  key = "show_glyph"
  type = "bool"
  label_key = "showGlyph.label"
  default = true

  [[widget.setting]]
  key = "show_label"
  type = "bool"
  label_key = "showLabel.label"
  default = true

[[service]]
id = "updates-service"
entry = "updates-service.luau"

[[panel]]
id = "updates-panel"
entry = "updates-panel.luau"
placement = "attached"
